version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: original
          files:
            - '**/*.go'
          allow:
            - $gostd
            - github.com/adamvduke/bcrypt-cli
            - github.com/adamvduke/cli-reader
            - github.com/alecthomas/kingpin/v2
            - github.com/google/go-cmp/cmp
            - golang.org/x/crypto/bcrypt
            - golang.org/x/term
          deny:
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package.
            - pkg: "github.com/instana/testify"
              desc: It's a fork of github.com/stretchr/testify.
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*bytes.Buffer).WriteString # WriteString is documented as always returning a nil error
        - crypto/rand.Read # crypto/rand.Read is documented as always filling the buffer and never returning an error
    gocognit:
      min-complexity: 20
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 10
    godot:
      scope: toplevel
      exclude:
        - '^fixme:'
        - '^todo:'
      capital: true
      period: true
    lll:
      line-length: 140
      tab-width: 1
    nestif:
      min-complexity: 2
    nlreturn:
      block-size: 10
    staticcheck:
      checks:
        - all
    varnamelen:
      max-distance: 6
      min-name-length: 3
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com)
        - prefix(golang.org)
        - alias
        - localmodule
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
